# Generated by Django 2.0.7 on 2018-07-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0002_auto_20180718_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='correct_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Answered Correct'),
        ),
    ]
