# Generated by Django 2.0.5 on 2018-07-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0003_team_correct_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
